"""Public interfaces for the MedRec Research Library."""

from .adapters import (
    AdapterError,
    AdapterLaunchError,
    AdapterProcessError,
    AdapterProtocolError,
    AdapterTimeoutError,
    PredictionAdapter,
    ProcessPredictionAdapter,
)
from .comparison_protocol import (
    AdaptationBudget,
    ComparisonProtocolPacket,
    ComparisonProtocolV1_1,
    ComparisonQualificationAttempt,
    DecoderClass,
    DecoderProfile,
    IndependentEvaluationInput,
    QualificationGateResult,
    QualificationGateState,
    SelectionSplit,
    ThresholdSelectionRule,
)
from .comparison_scope import ComparisonScope
from .dataset import (
    DatasetManifest,
    DatasetPrivacy,
    DatasetSplit,
    MembershipDigestMethod,
    SplitName,
)
from .errors import ProtocolValidationError
from .evaluation import (
    ComparisonEvaluationResult,
    ComparisonOutcomes,
    EvaluationResult,
    JoinedComparisonBatch,
    OutcomeInterval,
    evaluate_comparison_predictions,
    evaluate_predictions,
    join_comparison_targets,
)
from .prediction import (
    ComparisonPredictionBatch,
    MedicationScore,
    PredictionRecord,
    TargetFreePrediction,
)
from .protocol_check import ProtocolCheckRecord
from .reference import ReferenceConfig, run_reference_slice
from .registry import (
    BaselineDefinition,
    BaselineReadiness,
    BaselineRegistry,
    ComparisonQualification,
    ReadinessEvidence,
    ReadinessGate,
    ReproductionLane,
    ReproductionProgram,
    ResearchMode,
    SourceIdentity,
    SourceStatus,
)
from .remote_executor import FrozenSchedule, RemoteExecutor, SSHConfig
from .run_record import ArtifactChecksum, RunParameter, RunParameterValue, RunRecord

__all__ = (
    "AdaptationBudget",
    "AdapterError",
    "AdapterLaunchError",
    "AdapterProcessError",
    "AdapterProtocolError",
    "AdapterTimeoutError",
    "ArtifactChecksum",
    "BaselineDefinition",
    "BaselineReadiness",
    "BaselineRegistry",
    "ComparisonEvaluationResult",
    "ComparisonOutcomes",
    "ComparisonPredictionBatch",
    "ComparisonProtocolPacket",
    "ComparisonProtocolV1_1",
    "ComparisonQualification",
    "ComparisonQualificationAttempt",
    "ComparisonScope",
    "DatasetManifest",
    "DatasetPrivacy",
    "DatasetSplit",
    "DecoderClass",
    "DecoderProfile",
    "EvaluationResult",
    "FrozenSchedule",
    "IndependentEvaluationInput",
    "JoinedComparisonBatch",
    "MedicationScore",
    "MembershipDigestMethod",
    "OutcomeInterval",
    "PredictionAdapter",
    "PredictionRecord",
    "ProcessPredictionAdapter",
    "ProtocolCheckRecord",
    "ProtocolValidationError",
    "QualificationGateResult",
    "QualificationGateState",
    "ReadinessEvidence",
    "ReadinessGate",
    "ReferenceConfig",
    "RemoteExecutor",
    "ReproductionLane",
    "ReproductionProgram",
    "ResearchMode",
    "RunParameter",
    "RunParameterValue",
    "RunRecord",
    "SSHConfig",
    "SelectionSplit",
    "SourceIdentity",
    "SourceStatus",
    "SplitName",
    "TargetFreePrediction",
    "ThresholdSelectionRule",
    "evaluate_comparison_predictions",
    "evaluate_predictions",
    "join_comparison_targets",
    "run_reference_slice",
)
